
Jonnitto:
  GoogleMaps:
    APIKey: null
    includeGoogleAPI: true
    includeFunction: true
    includeBackendJS: true
    includeCSS: true
    googleAPI: '//maps.google.com/maps/api/js?key={APIKey}&callback=initJonnittoGoogleMaps'
    cssClasses:
      map: jonnitto-googlemaps-mapview
      streetview: jonnitto-googlemaps-streetview
      both:
        wrapper: jonnitto-googlemaps-both-wrapper
        map: jonnitto-googlemaps-both-mapview
        streetview: jonnitto-googlemaps-both-streetview
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.GoogleMaps:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.GoogleMaps: true
